# Generated by Django 5.0.6 on 2024-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('consola_id', models.AutoField(primary_key=True, serialize=False)),
                ('consola_precio', models.IntegerField()),
                ('consola_descripcion', models.CharField(max_length=250)),
                ('consola_cantidad', models.IntegerField()),
                ('consola_estado', models.BooleanField(default=True)),
                ('consola_image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('juego_id', models.AutoField(primary_key=True, serialize=False)),
                ('juego_precio', models.IntegerField()),
                ('juego_descripcion', models.CharField(max_length=250)),
                ('juego_cantidad', models.IntegerField()),
                ('juego_estado', models.BooleanField(default=True)),
                ('juego_image', models.CharField(max_length=250)),
            ],
        ),
    ]
