# Generated by Django 5.0.6 on 2024-07-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageFunctions', '0002_contrato_consola_consola_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='consola_image',
            field=models.ImageField(upload_to='assets\\img'),
        ),
    ]
