# Generated by Django 5.0.6 on 2024-07-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageFunctions', '0003_alter_consola_consola_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='juego_image',
            field=models.ImageField(upload_to='assets\\img'),
        ),
    ]
