# Generated by Django 5.0.6 on 2024-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageFunctions', '0004_alter_videojuego_juego_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='juego_slug',
            field=models.SlugField(default=''),
        ),
    ]
